"use client";
import { S, Card, G, B, Q, P } from "@/legacyLibrary.jsx";
import { tk } from "@/theme.jsx";

/* ══════════════════════════════════════════════════════════════════════════
   HFT / LOW-LATENCY SOFTWARE ENGINEERING
   Rewritten Sep 2026. Every number is either measured in the debug_lab perf
   track (cited as lab perf/NN) or stated as an order of magnitude. Claims
   that were folklore in the previous version are corrected in the table.
   ══════════════════════════════════════════════════════════════════════════ */

export default function HftModule() {
  return (
    <div>
      <S title="What HFT software roles actually test">
        {/* content-check:sourced — every claim below is quoted from the linked public posting or page */}
        <B type="interview">
          Evidence, not stereotypes. From the firms' own postings and pages (Sep 2026): <strong>HRT</strong> asks for C/C++ or Python, CS fundamentals,
          "UNIX operating systems (we use Linux), system/processor performance, and network communication"; its core-dev team promises
          "deep knowledge of C++, OS internals, CPU architecture, and networking hardware and protocols". <strong>Optiver</strong> hires for
          performance-critical C++ on the execution path, next to FPGA components; candidate reports describe a fundamentals round on memory
          models, concurrency, networking and OS internals, and a design round that prefers low-latency problems. <strong>Graviton (Gurugram)</strong>
          asks for C/C++, algorithms, Linux, and prefers TCP/IP and Ethernet knowledge. <strong>Jane Street</strong> states it does not ask software
          engineers mental math or logic puzzles: long collaborative coding in the language you know best.
        </B>
        {/* content-check:end */}
        <G cols={2} items={[
          { t: "The spine (every firm)", d: "C++ depth (object model, lifetimes, templates, atomics) · Linux internals · CPU, cache and memory behaviour · networking · clean algorithms explained while you code." },
          { t: "Firm-specific extras", d: "Mental-math or probability screens at some market-making firms; FPGA/hardware familiarity for execution teams; Python for research tooling. Prepare these per application, not up front." },
          { t: "What they are really scoring", d: "Can you reason from mechanism to measurement? 'It is slow because of X, here is the counter that proves it, here is the fix and the number after.' Recited tricks without evidence score zero." },
          { t: "Your edge", d: "You read what the compiler emitted and you can prove a change with counters. Lead with that: it is rarer than another lock-free queue." },
        ]} />
      </S>

      <S title="The tick-to-trade path (know where the time goes)" c={tk.orange}>
        <Card title="Stages and orders of magnitude" color={tk.orange}>
          <div style={{ fontFamily: tk.mono, fontSize: "var(--fs-sm)", lineHeight: 1.9, color: tk.text }}>
            NIC receives packet<br />
            → kernel stack (IRQ, softirq, socket copy, wake-up) &nbsp;~5–15 µs, fat tail<br />
            → OR user-space polling / kernel bypass (DPDK, ef_vi, VMA, SO_BUSY_POLL) &nbsp;~1–2 µs, tight<br />
            → OR FPGA feed handler &nbsp;sub-µs<br />
            → decode binary feed message &nbsp;tens of ns<br />
            → update order book &nbsp;tens to hundreds of ns<br />
            → strategy decision &nbsp;ns to µs (this is where teams compete on code)<br />
            → encode order, hand to NIC &nbsp;hundreds of ns to µs<br />
          </div>
          <P>Exact numbers are firm- and hardware-specific; quote ranges and offer to measure. The design principle is one hot path with no allocation, no
            syscalls, no locks, warm caches and predictors; everything else (logging, risk reports, persistence) runs on other cores and talks to the hot path
            through queues.</P>
        </Card>
      </S>

      <S title="Folklore corrections (the previous version of this page repeated some of these)" c={tk.red}>
        <G cols={1} items={[
          { t: "\"Branchless min: b + (diff & (diff >> 31)) — zero mispredictions\"", d: "Undefined behaviour when a - b overflows (signed), and clang already emits a conditional move for std::min. Branchless code helps only when the branch is unpredictable AND both sides are cheap; when predictable, the cmov adds a data dependency the predictor would have speculated past. Verify with perf stat branch-misses and by reading the asm (lab perf/02)." },
          { t: "\"std::variant + std::visit: jump table, no indirection\"", d: "A visit is still an indirect jump (or a switch). What you gain is inlinable alternatives and no heap or vptr, not zero cost. Measure the site; monomorphic virtual calls are cheap too." },
          { t: "\"Mutexes involve syscalls (1–5 µs)\"", d: "An uncontended futex-based mutex is one atomic RMW on lock and one on unlock: ~20 ns, no syscall. The syscall (futex_wait/wake) and the context switch happen only under contention. Spinlocks trade a burning core for wake latency; they are not free either." },
          { t: "\"clock_gettime costs ~50 ns; RDTSC is free\"", d: "Measured here (lab perf/04): vDSO clock_gettime ~27 ns, rdtsc ~12 ns, serialized rdtscp+lfence ~24 ns. RDTSC needs calibration and serialization to time short regions correctly. Neither is free; both are fine for µs-scale work." },
          { t: "\"Replace the switch with a lookup table of function pointers\"", d: "A dense switch already compiles to a jump table. A function-pointer table adds an indirect CALL and blocks inlining, which is exactly what you wanted to avoid. Data tables (not code tables) are the good version of this idea." },
          { t: "\"The HFT compile line: -O3 -march=native -fno-exceptions -fno-rtti -flto\"", d: "Exceptions cost nothing on the non-throwing path with table-based unwinding; -fno-exceptions buys code size and a design discipline. -march=native ties the binary to the build host (SIGILL elsewhere). -O3 is sometimes slower than -O2 via code bloat. Each flag is a measurement, not a belief (see the question on flags below)." },
          { t: "\"acquire/release is free on x86\"", d: "Cheap, not free: plain loads and stores already have the ordering on TSO, so no fence is emitted, but atomicity and the compiler barrier still constrain optimization, and a seq_cst store costs a full fence (xchg). On AArch64 acquire/release are LDAR/STLR and cost real cycles." },
          { t: "\"Never use std::map or std::unordered_map\"", d: "A good default (pointer chasing, node allocation), but the real rule is: know your access pattern and size at startup. Flat sorted arrays, open-addressing tables and direct-indexed arrays for price levels replace them." },
          { t: "\"Prefetch fixes pointer chasing\"", d: "A prefetch helps only if you know the address at least one memory latency before you need it. In a linked list you don't. Restructure for memory-level parallelism (independent chains, batching) instead." },
        ]} />
      </S>

      <S title="Measurement" c={tk.amber}>
        <Q d="must" q="How would you measure a 200 ns code path reliably? What are RDTSC's pitfalls?" a={"Measure many iterations individually and report percentiles, never one number.\n\nMechanics:\n• Serialize the counter reads: lfence; rdtsc before the region, rdtscp; lfence after. Without it, out-of-order execution can read the counter before or after the work you meant to time. The serialized pair costs ~25 ns on the lab laptop (lab perf/04): on a 200 ns region that is ~10% overhead; know it and report it.\n• Convert ticks with a calibrated rate. The TSC is constant-rate and invariant on modern CPUs (constant_tsc / nonstop_tsc in /proc/cpuinfo) but its rate is not the core clock: use perf's cycles when you want cycles.\n• Pin the thread. It removes migration noise and any doubt about cross-core TSC alignment.\n• Keep inputs opaque and results alive (BENCH_KEEP) or the compiler deletes the work (lab perf/04).\n• Warm up, then take 1e5–1e6 samples; report p50 / p99 / p99.9 / max with the conditions (lab perf/05).\n\nPitfalls interviewers probe: unserialized rdtsc; assuming clock_gettime is free (~27 ns via vDSO here: fine for µs, not for ns); frequency scaling (TSC ticks at a constant rate while the core clock moves); virtualized TSC in VMs; and forgetting to measure the measurement itself."} />
        <Q d="must" q="Why report p99.9 rather than the mean? Where does tail latency come from, and which sources can you remove yourself?" a={"A trading system loses on its worst message, not its average one. The mean hides the one-in-a-thousand event that is 100x slower. p50 tells you the cost of your code; p99 / p99.9 / max tell you the cost of everything around it.\n\nSources, each with the counter that reveals it (lab perf/05):\n• page faults on first touch → getrusage minor faults; fix: pre-fault, MAP_POPULATE, mlock\n• preemption → /proc/self/status nonvoluntary_ctxt_switches; fix: pin, isolated cores, SCHED_FIFO (root)\n• migration → sched_getcpu() changes; fix: affinity\n• interrupts and timer ticks on the core → /proc/interrupts deltas; fix: IRQ affinity, nohz_full (root)\n• SMT sibling activity → scaling test; fix: idle siblings or SMT off\n• frequency and C-state transitions → governor; fix: performance governor, idle=poll (root)\n• allocation, syscalls, logging in the loop → ltrace -c / strace -c; fix: preallocate, move off the hot path\n• TLB misses on big tables → dTLB-load-misses; fix: huge pages\n\nIn the lab, pre-faulting a 64 MB table moved p99.9 from ~39 µs to ~7.6 µs without touching the hot loop, and the residual tail was attributed to preemption by the involuntary-switch counter. That is the shape of a good answer: mechanism → counter → fix → residual."} />
      </S>

      <S title="CPU, cache and memory" c={tk.cyan}>
        <Q d="hard" q="What does a branch mispredict cost, how do you prove a branch is the problem, and when is going branchless worse?" a={"Cost: the pipeline is flushed and refilled from the correct target, ~15–25 cycles on current x86 cores (lab perf/02 measured ~24 cycles per miss on the lab machine).\n\nProof: perf stat -e branches,branch-misses on good vs bad input. The signature is identical instruction counts with a large miss delta: sorted vs random data ran the same instructions and took 13x the time.\n\nBranchless (cmov / select / arithmetic) computes both sides and picks one. It wins when the branch is unpredictable and both sides are cheap. It loses when the branch is predictable (cmov adds a data dependency the predictor would have speculated through; loads on the untaken side still execute), when one side is expensive, or when the compiler already did it (if-conversion). Check the asm before hand-writing anything.\n\nThe folklore trick b + (diff & (diff >> 31)) is UB when a - b overflows and is usually slower than the cmov clang emits for std::min. Measure, don't recite."} />
        <Q d="must" q="What is false sharing, how do you detect it, and how do you fix it?" a={"Two cores write different variables that share a 64-byte cache line. Coherence works on whole lines, so each write pulls the line away from the other core (request-for-ownership) and back: logically independent data, physically contended. Symptom: a two-thread version scales worse than one thread, or an SPSC queue is slow although producer and consumer never touch the same field.\n\nDetect: a scaling experiment (same work, 1 thread vs 2 on separate cores); perf c2c (root) shows the contended lines and offsets; a tiny working set with a high L1/L2 miss rate is a hint.\n\nFix: give each concurrently-written hot variable its own line: alignas(64) or std::hardware_destructive_interference_size (the constant is compiler/target dependent and can affect ABI, so many codebases hardcode 64 and static_assert it). Separate read-mostly from write-heavy fields. In an SPSC queue keep head and tail on separate lines and keep a private cached copy of the other side's index so the shared line is read rarely. Don't pad everything: padding costs cache and bandwidth; pad what is written concurrently."} />
        <Q d="hard" q="AoS vs SoA: when does SoA win, when does it lose, and how do you verify the choice?" a={"Caches move 64-byte lines. A loop touching one 8-byte field of many records under AoS drags whole records through the cache for 12% line utilization, with a strided access no vectorizer likes. SoA makes that field contiguous: full lines, unit stride, SIMD.\n\nSoA loses when a loop touches all fields of a few records (several streams instead of one; the hardware prefetcher tracks a limited number of streams), when access is random by record (a record is now spread over N lines instead of one), and when per-record logic dominates. AoSoA (blocks of 8–16 records in SoA layout) is the usual compromise for SIMD plus locality.\n\nVerify: perf stat L1-dcache-load-misses and LLC-load-misses per element, plus bytes per second. A layout change that halves misses but not time means you were bound elsewhere (lab perf/02: stride-1 vs stride-16 shows how the prefetcher hides misses)."} />
        <Q d="must" q="Rough cost of L1, L2, L3 and DRAM, and how do you make a chain of dependent lookups faster?" a={"Order of magnitude on a current x86 core: L1 ~4–5 cycles (~1 ns), L2 ~14 cycles, L3 ~40–80 cycles, DRAM ~80–120 ns (the lab machine measured ~125 ns per dependent miss in a 64 MB table). Quote ranges and offer to measure.\n\nA dependent chain (probe → node → next) pays a full latency per step because the next address is unknown until the previous load returns. To go faster:\n• memory-level parallelism: interleave K independent chains (batch lookups, software pipelining) so K misses overlap; an out-of-order core tracks ~10+ outstanding misses\n• software prefetch only when the address is known at least one memory latency ahead; useless for a plain linked list\n• shrink: compact keys, open-addressing tables with inline values, fewer indirections\n• huge pages: a 64 MB table is 16K 4-KiB pages but 32 2-MiB pages; fewer TLB misses per probe\n• layout: keep probed fields together, move cold metadata away\n• algorithm: a sorted array with branchless binary search, or a direct-indexed array when the key space is small (price levels)."} />
        <Q d="medium" q="Page fault vs TLB miss vs cache miss: what is each, what does it cost, and how does each show up?" a={"• Cache miss: the line is not in L1/L2/L3; the core waits for DRAM (~100 ns) but stays in user mode. Counters: L1-dcache-load-misses, LLC-load-misses; IPC drops.\n• TLB miss: the virtual→physical translation is not cached; the page walker reads page tables (tens of cycles if the entries are cached, hundreds if not). Counter: dTLB-load-misses. Fix: 2 MiB huge pages cover 512x more memory per entry.\n• Page fault: the page is not mapped at all (first touch, copy-on-write, swapped out). A trap into the kernel: microseconds. Counters: minor/major faults (getrusage, perf stat -e page-faults). Fix: pre-fault (MAP_POPULATE, mlock), never allocate on the hot path.\n\nThey nest: a page fault implies TLB and cache misses afterwards. In lab perf/05 the first touch of each 4 KiB page cost two faults: the read mapped the shared zero page, the write then copied it."} />
      </S>

      <S title="Memory and allocation" c={tk.violet}>
        <Q d="must" q="Why do latency-critical systems avoid malloc on the hot path, and what do they use instead?" a={"Not because malloc is slow on average (an uncontended thread-cache hit is ~20–50 ns) but because it is unpredictable: first-touch page faults on fresh arenas, lock contention between threads, madvise/trim syscalls when memory is returned, fragmentation over a long day, and a large free() turning into munmap. With a budget of a few hundred ns per message, an occasional 20 µs is a failure.\n\nInstead: allocate everything at startup (pools, arenas, free lists sized for the worst case), recycle objects, fixed-capacity ring buffers, placement-new into pre-owned storage, mlock and pre-fault the arenas. Remove implicit allocations: std::string beyond the SSO limit, std::function with captures, iostreams, exceptions on the happy path, vector growth (reserve), map/unordered_map nodes.\n\nVerify: ltrace -c, or an LD_PRELOAD counter, shows zero malloc/free calls from the hot loop in steady state."} />
        <Q d="hard" q="A profile of a strategy process shows 30% in memcpy and 20% in malloc. Walk me through what you do." a={"First, don't trust the symbol alone. perf report --no-children with call graphs (--call-graph dwarf) shows WHO calls memcpy and malloc; it is often one message-copying path or std::string / std::vector churn in a parser. Then quantify sizes and counts (ltrace -c, or an LD_PRELOAD shim histogramming malloc sizes): a million 32-byte allocations is a different problem from a few huge copies.\n\nFix in order of leverage: eliminate copies (parse in place, views/spans, zero-copy from the receive ring), eliminate allocations (preallocated message pools, reserve, SSO-sized strings, an arena per message), and only then make the remaining copies faster (alignment, size-class specialization).\n\nProve it: same input, pinned, A/B interleaved, p50/p99 per message and total throughput, and re-profile to show the symbols are gone rather than moved. Report the residual and what it is."} />
      </S>

      <S title="Concurrency" c={tk.emerald}>
        <Q d="must" q="Design a single-producer single-consumer ring buffer. Which memory orders, why, and what breaks with a second producer?" a={"Fixed power-of-two capacity, indices masked; head written by the consumer, tail by the producer, each on its own cache line, plus a private cached copy of the other side's index.\n\nProducer push:\n  t = tail.load(relaxed)                       // my own index\n  if (t - head_cached == N) { head_cached = head.load(acquire); if (t - head_cached == N) return false; }\n  buf[t & mask] = item\n  tail.store(t + 1, release)                   // publish: the slot write happens-before a consumer that acquires this\nConsumer pop mirrors it: load head relaxed, refresh tail_cached with acquire when it looks empty, read the slot, store head release.\n\nWhy those orders: the release store of the publishing index and the acquire load on the other side create the happens-before edge that makes the slot data visible. Relaxed is enough for your own index because only you write it. The cached copies avoid touching the shared line on every operation, which is a large win under load. Wait-free: no CAS, no retry loop.\n\nWith two producers both would read the same tail and write the same slot. You need an atomic claim (fetch_add or CAS on tail) and then a per-slot sequence number so the consumer can tell a claimed slot from a filled one (the Vyukov bounded MPMC design), or one SPSC queue per producer and a consumer that polls them. ABA appears once slots are reused with CAS on raw indices; sequence numbers fix it. On x86 the release/acquire pair costs no fence; on AArch64 it is STLR/LDAR."} />
        <Q d="hard" q="acquire/release vs seq_cst on x86 and AArch64: what do they cost, and when do you actually need seq_cst?" a={"x86 (TSO): plain loads already act as acquire and plain stores as release, so acquire/release atomics compile to ordinary MOVs plus a compiler barrier: no fence. A seq_cst store must be ordered before later loads (StoreLoad), which TSO does not give you, so it compiles to a locked xchg: a full fence, ~20–40 cycles and a store-buffer drain. seq_cst loads stay plain MOVs.\n\nAArch64 (weak): acquire load = LDAR, release store = STLR; seq_cst uses the same instructions (they are RCsc), so acq/rel and seq_cst cost about the same, and relaxed = LDR/STR.\n\nYou need seq_cst when correctness depends on a single total order across DIFFERENT atomics: the store-buffer / Dekker pattern where each thread sets its own flag then reads the other's, and both must not read 'false'. Producer/consumer handoff, flags, reference counts and queues need only acquire/release.\n\nRule: default to seq_cst; drop to acq/rel where you can name the happens-before edge you rely on; use relaxed only for counters nobody synchronizes on. Verify with TSan for races and with the asm for cost (concurrency track)."} />
        <Q d="hard" q="Mutex vs spinlock vs lock-free: what actually happens on an uncontended lock and on a contended one?" a={"Uncontended std::mutex (futex-based): lock is one atomic compare-exchange, unlock one atomic exchange or store: ~20 ns, no syscall.\nContended: the waiter spins briefly (adaptive), then futex_wait, a syscall that sleeps in the kernel; the holder's unlock must futex_wake it: microseconds, a context switch, and the lock word's cache line ping-ponging between cores.\n\nSpinlock: the same atomic RMW, but a waiter burns its core polling; wake latency is a cache-line transfer (~100 ns) instead of a scheduler round trip. Right only when critical sections are shorter than a context switch, holders are never preempted (pinned, isolated cores) and the CPU is affordable. Use test-and-test-and-set with a pause instruction and back-off.\n\nLock-free: guarantees progress, not speed; the CAS loop still contends on the same line. For latency-critical paths the goal is to avoid sharing altogether: partition data by thread and pass messages through SPSC queues, so no lock and no CAS is on the hot path."} />
      </S>

      <S title="Linux" c={tk.amber}>
        <Q d="must" q="Why do trading systems busy-poll instead of using epoll or interrupts, and what does it cost?" a={"The interrupt-driven receive path costs: NIC interrupt → softirq → socket buffer → wake the sleeping thread → scheduler places it → return from epoll_wait. Several microseconds, and worse, variable. A thread that spins on the NIC receive ring (kernel bypass: DPDK, Solarflare ef_vi/Onload, Mellanox VMA; or socket-level SO_BUSY_POLL) sees the packet within ~1 µs of arrival with far less jitter, because nothing has to be woken.\n\nCosts: one core per polling thread at 100% CPU, power and heat; the core must be isolated (isolcpus, IRQ affinity) or the spinner gets preempted and the benefit evaporates; with bypass you give up the kernel's protocol stack, which the framework reimplements in user space. Real designs mix: spin on the market-data and order cores, epoll on control-plane and logging threads."} />
        <Q d="hard" q="What do you do to a Linux box for low latency, and which steps need root?" a={"CPU: performance governor (cpupower); disable deep C-states (idle=poll or /dev/cpu_dma_latency); decide on turbo (determinism vs speed); SMT off or siblings idle; isolate cores (isolcpus=, nohz_full=, rcu_nocbs= on the kernel command line); pin threads; SCHED_FIFO for the critical thread.\nInterrupts: route all IRQs away from isolated cores (/proc/irq/*/smp_affinity), stop irqbalance; timer migration off.\nMemory: huge pages (hugetlbfs, or THP with madvise), mlockall, pre-fault, NUMA-local allocation (numactl), no THP compaction stalls, no swap.\nNetwork: kernel bypass or SO_BUSY_POLL; RSS/RFS steering to the right core; ring sizes; TCP_NODELAY; hardware timestamps with PTP.\nProcess: no logging or allocation on the hot path; audit/security agents and perf sampling off on production cores.\n\nRoot needed for: governor, C-states, kernel command line, IRQ affinity, real-time priority (or rtprio limits), mlock beyond RLIMIT_MEMLOCK, hugetlbfs. Without root you still get: taskset affinity, pre-faulting, MAP_POPULATE, madvise(MADV_HUGEPAGE) when THP is in madvise mode, and all the measurement (labs perf/01 and perf/05)."} />
      </S>

      <S title="Networking" c={tk.sky}>
        <Q d="must" q="Market data over UDP multicast and orders over TCP: why that split, and what does the kernel network stack cost?" a={"Multicast: one packet from the exchange reaches every subscriber with no per-client state and no retransmission stalls. Loss is handled by sequence numbers (gap detection), a recovery channel and periodic snapshots; feeds usually come as redundant A/B streams and the handler takes whichever copy of a sequence number arrives first.\n\nOrders over TCP: reliability and ordering matter more than nanoseconds, and exchanges require a session protocol anyway; you disable Nagle (TCP_NODELAY), keep connections warm, and pre-build messages.\n\nKernel stack cost per small packet: interrupt/NAPI poll, softirq protocol processing, skb allocation, copy to the socket buffer, wake-up: roughly 5–15 µs end-to-end on a tuned box with a fat tail. User-space bypass brings that to ~1–2 µs with stable tails; FPGA handlers go below a microsecond.\n\nTools: SO_TIMESTAMPING and NIC hardware timestamps to see where time goes; tcpdump/pcap with NIC timestamps as an external reference; ethtool -S for drops."} />
        <Q d="hard" q="How do you find where a message loses time from NIC-in to NIC-out?" a={"Instrument, don't guess. Timestamp each stage with the TSC (received in the poll loop, decoded, book updated, decision made, order encoded, handed to the NIC) into preallocated ring buffers, and build per-stage histograms offline. Use NIC hardware receive/transmit timestamps, PTP-disciplined, to bound the total and to separate transport from processing.\n\nCorrelate outliers with counters (page faults, context switches, IRQs on the core) and with an independent capture (pcap on a span port) to rule out the NIC and driver. Look at the distribution per stage, not the mean: the stage with the fattest tail is the one to fix first even when its p50 is tiny. Then reproduce that stage in isolation as a microbenchmark (lab perf/04 rules) and iterate."} />
      </S>

      <S title="C++ and codegen" c={tk.pink}>
        <Q d="hard" q="What does a virtual call really cost in a hot loop, and what are the alternatives?" a={"The call itself: load the vptr, load the function pointer, indirect call. The indirect-branch predictor handles it; at a monomorphic site it costs a few cycles, like a direct call. A site that alternates types mispredicts (~20 cycles).\n\nThe real cost is what it PREVENTS: the callee cannot be inlined, so the optimizer cannot hoist, vectorize or constant-fold across the boundary. That is usually far more than the call.\n\nAlternatives: templates / CRTP (static dispatch, full inlining); std::variant + std::visit (a switch or jump table, still an indirect jump, but inlinable bodies and no heap or vptr); sort work by type so each batch is monomorphic; devirtualization via final, LTO and PGO (the compiler speculates the likely type and inlines behind a guard). Say: measure; it depends on whether the site is monomorphic and whether inlining unlocks anything."} />
        <Q d="medium" q="What do -fno-exceptions, -fno-rtti, -O3, -march=native, LTO and PGO actually buy, and what do they cost?" a={"-fno-exceptions: with table-based unwinding the non-throwing path costs nothing at runtime; what you save is code size (unwind tables, landing pads, cleanups) and some optimization constraints around calls that may throw. You lose exceptions, including from the standard library. Firms use it as a design discipline more than a speedup.\n-fno-rtti: removes typeinfo; smaller binaries; breaks dynamic_cast and typeid. Neutral for hot loops.\n-O3 vs -O2: more aggressive inlining, unrolling and vectorization; sometimes faster, sometimes slower via code bloat. Measure per binary.\n-march=native: enables the build host's ISA; the binary may SIGILL on older CPUs. Name the production CPU explicitly instead.\nLTO: cross-TU inlining and dead-code removal; typically a few percent; longer builds.\nPGO: profile-driven inlining, layout and branch weights; often the largest single win for branchy code; needs representative profiles and a build pipeline that keeps them fresh.\n\nNone of these replace fixing the algorithm or the data layout; they are the last 10–20%, and each is a measurement, not a belief."} />
      </S>

      <S title="Design" c={tk.rose}>
        <Q d="must" q="Design a limit order book for one instrument at 10M messages per second: add, modify, cancel, best bid/ask." a={"Requirements first: 10M messages/s means ~100 ns per message all-in; operations are add (price, qty, id), cancel by id, modify (reduce qty in place; cancel+add if the price changes), best bid/ask and top-N levels; single-threaded and deterministic; no allocation after startup.\n\nStructure:\n• Price levels: prices are ticks on a bounded grid, so an array indexed by (price − base) / tick gives O(1) level access; separate arrays for bids and asks. For wide or sparse ranges, a two-level scheme (a bitmap of non-empty levels, or chunks) keeps 'next non-empty level' O(1) or amortized.\n• Each level: total quantity, order count, and an intrusive FIFO list of orders (time priority) with nodes from a preallocated pool.\n• Order id → order: an open-addressing hash table sized for the day (or a direct array if ids are dense per session); never rehash on the hot path.\n• Best bid/ask: keep the index; on removal walk toward worse prices, or find-first-set on the bitmap to skip empty levels in O(1).\n\nWhy not std::map<price, level>: pointer chasing, allocation per node, a cache miss per probe. Why intrusive lists: cancel by id is O(1) with no search.\n\nMaturity signals: sequence-number gap handling and snapshot recovery; a replayable input format for tests; hot fields (level qty) separated from cold (order details); a compact layout with static_assert(sizeof); per-operation benchmarks reported as percentiles."} />
      </S>

      <S title="Drills that back these answers" c={tk.emerald}>
        <G cols={2} items={[
          { t: "Measurement", d: "labs perf/01 (noise floor, pinning), perf/04 (microbenchmark traps, timer costs), perf/05 (tail latency, page faults)." },
          { t: "Counters and profiling", d: "labs perf/02 (branch and cache counters), perf/03 (hot line in an optimized C++ binary, inlining, stripped binaries)." },
          { t: "Concurrency", d: "Library guide 07 (memory models) and the concurrency track: TSan, SPSC three ways, memory orders on x86/AArch64, locks with futex counts, the store-buffer litmus." },
          { t: "Linux and networking", d: "Guides 17 (Linux for low latency) and 18 (networking for trading systems) plus the systems track: malloc, syscalls, busy-poll vs epoll, TCP_NODELAY, kernel timestamps." },
          { t: "C++ depth", d: "Prep modules Object Model, Memory/Move/RAII, Concurrency & Atomics, Linking & ABI; Library guides 05, 06, 16." },
          { t: "Design", d: "Order book, feed handler, log pipeline, cache, tick store, timer wheel: Library guide 22. Whiteboard the order book from memory in 20 minutes, then run a timed design mock (Mock Interviews module)." }, 
          { t: "Microarchitecture and method", d: "Guide 19 (x86 field guide) and Guide 20 (the investigation playbook) turn these answers into a procedure you can run on a real box." },
        ]} />
        {/* content-check:sourced */}
        <B type="tip">Mental math and probability: prepare a small module only when applying to a firm known to screen for it (some market makers do for certain tracks). Jane Street's own page says its engineering loop does not.</B>
        <P style={{ marginTop: 12 }}>
          Sources: <a href="https://www.hudsonrivertrading.com/work-at-hrt/" target="_blank" rel="noopener noreferrer">HRT · Work at HRT</a> ·{" "}
          <a href="https://optiver.com/working-at-optiver/career-opportunities/8373619002/" target="_blank" rel="noopener noreferrer">Optiver · Low Latency Execution Systems Engineer</a> ·{" "}
          <a href="https://job-boards.greenhouse.io/gravitonresearchcapital/jobs/4004920002" target="_blank" rel="noopener noreferrer">Graviton · Software Engineer (C++)</a> ·{" "}
          <a href="https://www.janestreet.com/preparing-for-a-software-engineering-interview/" target="_blank" rel="noopener noreferrer">Jane Street · Preparing for a Software Engineering Interview</a>
        </P>
        {/* content-check:end */}
      </S>
    </div>
  );
}
