"use client";
import { S, Card, G, B, Q, P } from "@/legacyLibrary.jsx";
import { tk } from "@/theme.jsx";

/* ══════════════════════════════════════════════════════════════════════════
   MARKET MICROSTRUCTURE FOR ENGINEERS
   Enough structure to know what the code you write is for, and to tell when
   a result is an artifact. Venue rules differ; every mechanism below is
   stated as the common case with the variation named.
   ══════════════════════════════════════════════════════════════════════════ */

export default function QuantMicroModule() {
  return (
    <div>
      <S title="Why an engineer needs this at all">
        <B type="interview">
          You are not being screened as a trader. You are being screened for whether the person writing the order book, the feed
          handler or the risk check <strong>understands what those things are for</strong>. The difference shows up immediately: an engineer
          who knows what queue position is will not write a book that rebuilds a level on every update, and will notice when a
          backtest fills at the mid.
        </B>
        <G cols={2} items={[
          { t: "The bar for a software role", d: "Vocabulary without hesitation, the mechanism behind each term, and one sentence on why it constrains the system you would build. Not pricing models, not alpha." },
          { t: "The tell they listen for", d: "Whether you connect a market concept to a code consequence. 'Queue position matters, so a modify that loses priority is a different operation from one that keeps it' is the whole game." },
          { t: "What to avoid", d: "Confident claims about how any specific firm makes money, or repeating something you read once about a strategy. Say what the mechanism is; say you do not know the rest." },
          { t: "Venue variation", d: "Almost every rule here has exceptions by asset class and exchange. Naming that you know the rule varies is worth more than stating one venue's rule as universal." },
        ]} />
      </S>

      <S title="The limit order book, precisely" c={tk.cyan}>
        <Card title="What the structure actually is" color={tk.cyan}>
          <P>A limit order book is two sorted collections of resting orders: bids, sorted by price descending, and asks, sorted
            ascending. Each price level holds a queue of orders. The highest bid and lowest ask are the <strong>best bid and offer</strong>;
            the gap between them is the <strong>spread</strong>; their average is the <strong>mid</strong>. The quantity resting at and near the
            touch is the <strong>depth</strong>.</P>
          <div style={{ fontFamily: tk.mono, fontSize: "var(--fs-sm)", lineHeight: 1.9, color: tk.text, marginTop: 12 }}>
            &nbsp;&nbsp;ASKS &nbsp;&nbsp; 100.03 &nbsp; 800 &nbsp;&nbsp;<span style={{ color: tk.textDim }}>← depth away from touch</span><br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 100.02 &nbsp; 500<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style={{ color: tk.rose }}>100.01 &nbsp; 200</span> &nbsp;&nbsp;<span style={{ color: tk.textDim }}>← best offer</span><br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style={{ color: tk.textDim }}>spread = 0.02 · mid = 100.00</span><br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style={{ color: tk.emerald }}>&nbsp;99.99 &nbsp; 300</span> &nbsp;&nbsp;<span style={{ color: tk.textDim }}>← best bid, a FIFO queue of orders</span><br />
            &nbsp;&nbsp;BIDS &nbsp;&nbsp; &nbsp;99.98 &nbsp; 900<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;99.97 &nbsp; 400<br />
          </div>
        </Card>
        <G cols={1} items={[
          { t: "Matching: price first, then usually time", d: "A better price always wins. Within a price level the common rule is time priority — first in, first filled — which is what makes queue position a real asset. Some futures and options products allocate pro-rata by size instead, and some use a hybrid that gives a share to the first order at a new price. Which rule the venue uses changes the optimal order size completely, so ask." },
          { t: "Aggressive versus passive", d: "An order that crosses the spread and executes immediately takes liquidity; one that rests in the book makes it. Taking pays the spread and gets certainty; making earns the spread and gets uncertainty. Almost every question in this area is about that trade." },
          { t: "The tick size is a floor on the spread", d: "The spread cannot be finer than one tick. When the tick binds — the spread sits at one tick nearly always — you can no longer compete by quoting a better price, because there is no better price. Competition moves entirely to being earlier in the queue, which is to say it moves to latency and to how you manage priority. This is the single most important structural fact for an engineer to internalize." },
          { t: "Data representations", d: "Market-by-price aggregates each level to a total quantity; market-by-order carries every individual order and lets you compute your own queue position. MBO is far larger and is the reason feed handlers care about allocation and cache layout. If you only have MBP you must infer your position, and the inference is wrong exactly when it matters." },
        ]} />
      </S>

      <S title="Order types, and what each is really for" c={tk.violet}>
        <G cols={2} items={[
          { t: "Limit", d: "Execute at this price or better; rest if it cannot. The default building block. Price certainty, no fill certainty." },
          { t: "Market", d: "Execute now at whatever is there. Fill certainty, no price certainty. In a thin book this walks several levels; most professional systems avoid it in favour of an aggressive limit with a cap." },
          { t: "IOC — immediate or cancel", d: "Take whatever is available right now, cancel the rest. The workhorse of aggressive trading: it bounds your risk to the book you already saw and leaves nothing resting to be picked off." },
          { t: "FOK — fill or kill", d: "All of it now or none of it. Used when a partial fill is worse than no fill, typically because it is one leg of something." },
          { t: "Post-only", d: "Reject rather than take. Guarantees you are the maker, so you earn the rebate rather than paying the fee, and guarantees you never cross by accident when your view of the book is stale." },
          { t: "Iceberg / reserve", d: "Show a slice, hide the rest. Reduces information leakage; typically the hidden part loses time priority when each slice refreshes, which is a real cost." },
          { t: "Pegged / midpoint", d: "Track a reference price rather than a fixed one. Midpoint pegs trade inside the spread, common in dark venues." },
          { t: "Auction orders", d: "Market- and limit-on-close and their opening equivalents participate only in the auction. Auctions concentrate a great deal of volume into one crossing price, which is why they matter far beyond their share of the trading day." },
        ]} />
        <B type="tip">
          The engineering reading of this list: order types are a protocol, and each one exists because some race or leakage made
          the naive version lose money. Post-only exists because your book view is stale. IOC exists because resting is a liability.
        </B>
      </S>

      <S title="The three questions worth being genuinely good at" c={tk.amber}>
        <Q d="must" q="Why does a market maker care about queue position?"
           a={"Because under time priority, position in the queue determines both whether you fill and — much more importantly — which fills you get.\n\nThe mechanical part: at a level with 300 lots ahead of you, nothing reaches you until 300 lots have traded. If you are first, you trade almost immediately.\n\nThe part that is the actual answer: the fills you get at the back of the queue are the bad ones. A level gets fully consumed when there is real pressure — when someone is pushing through size because the price is about to move. So the back of the queue fills mostly in exactly the states where the price is about to move against you. The front of the queue fills on ordinary two-sided flow that goes nowhere. Same price, same instrument, systematically different outcome. Queue position is not a speed convenience; it is a selection effect on which trades you participate in.\n\nThe consequences that show up in code. Queue position is earned by being early and destroyed by most modifications — on most venues, increasing the size of a resting order or changing its price sends it to the back, while decreasing size usually keeps priority. So 'cancel and replace' and 'modify down' are completely different operations with completely different economics, and a system that treats them the same is quietly throwing away the asset. The same fact explains why joining a new price level the instant it forms is worth so much: the queue is empty, and everyone knows it, which is what turns it into a latency race.\n\nWhen the tick size binds and the spread is always one tick, this stops being one consideration among many and becomes the entire competition."} />
        <Q d="must" q="What is adverse selection, and why is it the central cost of providing liquidity?"
           a={"Adverse selection is the fact that your passive orders are filled by whoever most wants to trade against them, which is by definition the counterparty with the better information.\n\nThe asymmetry: your resting bid is a free option you have written to the market. Anyone may hit it. It gets hit when someone believes the price is going down, and it goes unfilled when the price is going up — that is, you buy right before prices fall and fail to buy right before they rise. Your fills are not a random sample of the market; they are conditioned on the other side wanting them.\n\nThis is why the spread exists. The spread is not a fee; it is compensation, and it has to cover three things: adverse selection (the informed-flow cost above), inventory risk (you now hold a position you did not choose and prices move while you unwind it), and operating cost. If the spread is narrower than the adverse selection cost, providing liquidity loses money no matter how efficient your systems are. Spreads widen in volatile or uncertain conditions because the adverse-selection term grew, not because anyone decided to charge more.\n\nHow it is measured: markouts. Take the mid at the moment of your fill, then look at the mid one second, ten seconds, a minute later. If your buys are systematically followed by the mid falling, you are being adversely selected, and the average of that quantity across fills is the cost in currency per share. This is a routine metric, not an exotic one, and it decomposes cleanly: effective spread is what you captured at the moment of the trade, realized spread is what you kept after the price moved, and the difference is the price impact you paid.\n\nThe engineer's version: the whole point of cancelling fast is to withdraw the option before it is exercised against you. Latency on the cancel path is not a performance nicety; it is directly the price of the option you are writing."} />
        <Q d="must" q="Why does latency have economic value here? Be specific — not 'faster is better'."
           a={"Three distinct mechanisms, and it is worth separating them because they stress different parts of a system.\n\n1. Taking a stale quote. A price moves on one venue or in a related instrument. Somebody's resting order elsewhere is now mispriced. Whoever reaches it first takes it. This is a pure race with a single winner, so the value is enormously convex in latency — being second is worth nothing at all, not slightly less. This is the mechanism that drives the tick-to-trade arms race and the one people mean by 'latency arbitrage'.\n\n2. Cancelling before you are taken. The same race from the other side. Your quote is the stale one, and your only defence is to pull it in time. Here latency directly reduces a cost you are already paying, which makes it valuable even to a firm that never wins a taking race. Note that this is a race between your cancel and someone else's take — both measured from the same market event — so what matters is your reaction time, not your absolute clock.\n\n3. Queue position. When a new price level forms, orders are timestamped in arrival order and the front of the queue is worth materially more than the back, for the adverse-selection reason above. Being early buys a better distribution of fills for as long as that level lives.\n\nWhat follows for the system. The value lives in the tail, not the mean: the trade you lose is the one where a page fault, a garbage-collection pause, a lock, a context switch or a full queue added microseconds at the wrong moment. That is why this domain obsesses over jitter and over the 99.9th percentile, why the hot path avoids allocation, syscalls and locks, and why measurement is done with hardware timestamps rather than with averages. An engineer who says 'I would look at the tail, not the mean' has answered the question correctly.\n\nThe honest caveat: latency's value is bounded by the mechanism. Once you are fast enough that the remaining variance is the exchange's, more speed buys nothing, and different strategies sit at completely different points on that curve. 'How fast is fast enough here?' is a better interview answer than 'as fast as possible'."} />
      </S>

      <S title="Vocabulary with the mechanism attached" c={tk.blue}>
        <G cols={1} items={[
          { t: "Effective spread, realized spread, price impact", d: "Effective spread measures what a trade cost against the mid at the moment it happened. Realized spread measures the same trade against the mid some interval later, so it captures what the liquidity provider actually kept. The difference between them is the price impact — the part the market took back. Reporting only one of the three is how a strategy looks profitable and is not." },
          { t: "Market impact and the square-root regularity", d: "Trading moves the price against you, and the effect is not linear in size. The widely reported empirical regularity is that impact grows roughly with the square root of the fraction of daily volume you trade, scaled by volatility. Treat this as a robust empirical observation rather than a law, but the shape matters: it is why large orders are sliced over time and why the cost of size is sublinear but real." },
          { t: "Toxicity", d: "A description of order flow that is systematically informed. Retail flow is generally considered less toxic than flow from a firm that trades on the same signal you do, which is the entire economic reason internalization and retail wholesaling exist as businesses." },
          { t: "Inventory risk and quote skewing", d: "A maker who has accumulated a long position is exposed to a fall and wants to reduce it. The standard mechanism is skewing: quote a slightly more attractive offer and a slightly less attractive bid so that the flow itself unwinds you. The reference model here is Avellaneda–Stoikov, which derives the optimal skew and spread from inventory and risk aversion." },
          { t: "Maker-taker and inverted venues", d: "Many venues rebate the maker and charge the taker, so a fill's economics depend on which side you were. Inverted venues do the opposite to attract takers. The consequence for routing is that the best displayed price is not always the best net price, and any system that ignores fees will route wrongly." },
          { t: "Auctions", d: "Opening and closing crosses match a large amount of accumulated interest at a single price computed to maximize executed volume. They matter to engineers because they are a distinct protocol with distinct order types, distinct timing, and a completely different risk profile from continuous trading." },
          { t: "Circuit breakers and price bands", d: "Venues halt or constrain trading when prices move too far too fast. For a system this means every component must handle a halt, a resumption and a reopening auction as normal states, not as errors — and a strategy that has never been tested through a halt has not been tested." },
          { t: "Self-trade prevention", d: "Exchanges provide mechanisms to stop a firm's own orders from matching each other. It matters because a firm running several strategies will otherwise trade with itself, paying fees for nothing and distorting its own metrics." },
        ]} />
      </S>

      <S title="Market data: the part you will actually build" c={tk.emerald}>
        <Q d="must" q="Describe how a market-data feed reaches your process, and what can go wrong."
           a={"The common shape: the exchange publishes a binary, sequence-numbered message stream over UDP multicast. Multicast because one publication reaches every subscriber; UDP because the retransmission and ordering guarantees of TCP are exactly the wrong trade when a late message is worthless.\n\nThat choice moves three responsibilities into your code.\n\nGaps. UDP drops and reorders. Every message carries a sequence number and your handler must detect a gap the moment it appears. The usual recoveries are a redundant A/B feed published on separate paths — you arbitrate by taking whichever copy arrives first and discarding the duplicate, which repairs most single-path losses with no latency cost at all — plus a retransmission request channel and periodic snapshots for a gap too large to fill.\n\nState. The stream is incremental: add, modify, cancel, trade. You rebuild the book by applying them in order, which means a gap does not merely lose one message, it invalidates your book from that point on. Deciding what to do while you are in a gap — most systems stop quoting rather than trade on a book they know is wrong — is a design question, not an implementation detail, and 'I would stop trading' is the answer that shows judgement.\n\nStartup. You join a stream already in progress, so you buffer live increments while you obtain a snapshot, then apply the buffered increments from the snapshot's sequence number forward.\n\nWhat goes wrong in practice, in rough order of frequency: your receive buffer overflows under a burst and the kernel drops silently, so you must monitor the drop counters rather than trusting that no news is good news; a slow consumer downstream backs up into the handler; the two feeds are not actually independent and a single failure takes both; and the book diverges subtly from the exchange's, which you catch only by reconciling against periodic snapshots. Bursts are the recurring theme — market data is intensely bursty at the open, at the close and on news, so capacity must be sized for the burst rather than the average."} />
        <Q d="medium" q="Why hardware timestamps, and what does a timestamp let you prove?"
           a={"Because without them you cannot tell whose fault a delay is, and that is usually the actual question.\n\nA timestamp taken by your application when it reads the message includes everything that happened before it: wire time, NIC, interrupt handling, the kernel network stack, the scheduler, and any time your thread spent not running. A timestamp taken by the NIC on arrival, or by a tap on the wire, excludes all of that. Subtract the two and you have measured your own stack rather than the market.\n\nWith timestamps at each boundary you can decompose a tick-to-trade latency into wire-to-kernel, kernel-to-application, decode, strategy decision, encode, and application-to-wire. Then an increase in the total is attributable to one stage rather than being an argument. On Linux the socket-level mechanism is SO_TIMESTAMPING with hardware support on the NIC; PTP keeps clocks disciplined so that timestamps from different machines can be compared at all.\n\nThe framing that lands in an interview: a timestamp turns a latency conversation from opinion into arithmetic. It is the same instinct as reading a performance counter instead of guessing why a loop is slow — and if you have done that with perf on a compiler or a kernel, say so, because it is the same skill and it transfers directly."} />
        <Q d="medium" q="A backtest fills every order at the mid. What is wrong, and what would you replace it with?"
           a={"Every passive fill in that simulation is a fill you would not have received, and every aggressive one is cheaper than reality.\n\nThe specific errors. Passively, you assume you traded when in truth you must first reach the front of a queue and then have someone trade against you — and the simulation grants that fill in precisely the states where a real fill would have been adverse. Aggressively, you assume the mid when you would have paid the offer, so you have deleted the spread, which for a high-turnover strategy is usually larger than the entire modelled edge. You have also ignored fees and rebates, which flip sign with your side and your venue, and you have ignored your own impact — in reality your order changes the book you are trading against.\n\nWhat to replace it with, in increasing order of fidelity: cross the spread rather than taking the mid, and add explicit fees; for passive orders, model queue position from market-by-order data and fill only when the volume ahead of you has actually traded through; add a latency model, so that your decision is made on the book as it was when the message reached you and your order arrives some microseconds later, into whatever the book has become; and for size, add an impact model.\n\nThe structural fix that is better than all of them: run the same code in the backtest and in production, driven by recorded data through the same interface, so that the simulation cannot see anything the live system would not have seen. Fidelity you get from architecture survives; fidelity you get from remembering to be careful does not."} />
      </S>

      <S title="How to study this without pretending to be a trader" c={tk.rose}>
        <G cols={2} items={[
          { t: "Read primary sources", d: "Exchange rulebooks and matching-engine specifications are public, precise, and nobody reads them. One venue's specification, read properly, teaches more than any summary — and citing a mechanism you read in a rulebook is credible in a way that a blog summary is not." },
          { t: "Build the book", d: "Implement a limit order book from a public sample of market-by-order data: add, cancel, modify, trade, with correct priority. You will meet queue position, the cost of modification, and the memory layout question in the only way that sticks." },
          { t: "Measure something real", d: "Compute markouts on any dataset you can obtain legally. Seeing the sign of adverse selection appear in your own numbers converts the concept from vocabulary into knowledge." },
          { t: "Stay in your lane", d: "For a software role, stop at mechanism. You do not need to have a view on whether a strategy is good; you need to know what the code is for and what would make its results a lie." },
        ]} />
        <B type="warn">
          Two things to never do in an interview. Do not assert how a particular firm makes money — you do not know, and the person
          across the table does. And do not present a strategy idea; it is not what a software loop is scoring, and it invites a
          conversation you cannot win. Describe mechanisms, ask what their system does, and say plainly when something is outside
          what you have worked on.
        </B>
      </S>
    </div>
  );
}
