"use client";
import { S, Card, G, B, Q, P } from "@/legacyLibrary.jsx";
import { tk } from "@/theme.jsx";

/* ══════════════════════════════════════════════════════════════════════════
   PROBABILITY UNDER PRESSURE
   For the quant-developer and HFT loops, where the probability round is a
   ninety-second reasoning test, not a measure-theory exam. Every result below
   is a standard textbook result; none of it is a claim about any firm.
   ══════════════════════════════════════════════════════════════════════════ */

export default function QuantProbModule() {
  return (
    <div>
      <S title="What this round is actually testing">
        <B type="interview">
          Not recall. The interviewer wants to watch you <strong>choose a tool and commit</strong>. A candidate who says
          &ldquo;this is a sum of things, so linearity, and I do not need independence&rdquo; and then computes it has already passed;
          a candidate who silently writes the right integral has not shown anything. Say the sample space out loud, name the tool,
          compute, then sanity-check against an extreme case.
        </B>
        <G cols={2} items={[
          { t: "Scored", d: "Correct framing, a named technique, an arithmetic answer, and one sanity check. Recovering cleanly from a wrong turn scores higher than a lucky right answer." },
          { t: "Not scored", d: "Speed alone, memorized puzzle answers, or measure theory. If you recognize the puzzle, say so and derive it anyway." },
          { t: "The developer bar", d: "For engineering roles the probability is a filter, not the job. You need fluency in the eight tools below and the twelve classics, not research depth." },
          { t: "Where it reappears", d: "In the job it comes back as Monte Carlo correctness, variance of an estimator, and spotting that a backtest number is selection bias." },
        ]} />
      </S>

      <S title="The eight tools, and the shape that signals each" c={tk.cyan}>
        <Card title="Recognition table" color={tk.cyan}>
          <G cols={1} items={[
            { t: "1 · Linearity of expectation", d: "SHAPE: 'expected number of …'. Write the count as a sum of indicators, take E of each, add. Independence is NOT required — this is the whole reason the tool is so strong. Fixed points of a random permutation: n indicators each with P = 1/n, so E = 1." },
            { t: "2 · Indicator variables", d: "SHAPE: counting anything. E[1_A] = P(A). Pairs with linearity in almost every 'expected number' question. For variance you do need the covariance terms, and there independence matters again." },
            { t: "3 · Conditioning / first-step analysis", d: "SHAPE: a process that repeats, 'expected time until …'. Condition on the first step, write E = 1 + Σ P(step) · E[state after]. Solve the small linear system. This handles most waiting-time and random-walk questions." },
            { t: "4 · Symmetry and exchangeability", d: "SHAPE: 'what is the probability that A comes before B', shuffles, random orderings. If relabelling the objects leaves the distribution unchanged, the answer is 1/k by symmetry. Say why the relabelling is valid; that sentence is the answer." },
            { t: "5 · Bayes / reversing the conditional", d: "SHAPE: a test, a signal, evidence. P(H|E) = P(E|H)P(H) / P(E). The trap is always the base rate. Odds form is faster: posterior odds = prior odds × likelihood ratio." },
            { t: "6 · The tail-sum formula", d: "SHAPE: a non-negative integer variable whose CDF is easier than its PMF. E[X] = Σ_{k≥1} P(X ≥ k). Continuous version: E[X] = ∫₀^∞ P(X > t) dt. Turns 'expected maximum' problems into one integral." },
            { t: "7 · Memorylessness", d: "SHAPE: geometric or exponential waiting. P(X > s+t | X > s) = P(X > t). 'You have already waited an hour' changes nothing. Also gives the minimum of exponentials: min of Exp(λᵢ) is Exp(Σλᵢ), and it is the i-th one with probability λᵢ/Σλ." },
            { t: "8 · Martingales and optional stopping", d: "SHAPE: a fair game with a stopping rule; gambler's ruin; 'expected time to see the pattern'. If Mₙ is a martingale and τ is a bounded-enough stopping time, E[M_τ] = E[M₀]. This one sentence solves a surprising number of hard-looking questions." },
          ]} />
        </Card>
        <B type="tip">
          Reach for them in that order. Roughly: is it a count? (1,2) Is it a repeating process? (3) Is there a relabelling? (4)
          Is there evidence? (5) Is the CDF nicer? (6) Is it a waiting time? (7) Is there a fair game and a stopping rule? (8)
        </B>
      </S>

      <S title="Distributions you must know cold" c={tk.violet}>
        <Card title="Mean and variance without thinking" color={tk.violet}>
          <div style={{ fontFamily: tk.mono, fontSize: "var(--fs-sm)", lineHeight: 2, color: tk.text }}>
            Bernoulli(p) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mean p &nbsp;·&nbsp; var p(1−p)<br />
            Binomial(n,p) &nbsp;&nbsp;&nbsp; mean np &nbsp;·&nbsp; var np(1−p)<br />
            Geometric(p) &nbsp;&nbsp;&nbsp;&nbsp; mean 1/p &nbsp;·&nbsp; var (1−p)/p² &nbsp;&nbsp;<span style={{ color: tk.textDim }}>(trials until first success, support 1,2,…)</span><br />
            Poisson(λ) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mean λ &nbsp;·&nbsp; var λ<br />
            Exponential(λ) &nbsp;&nbsp;&nbsp; mean 1/λ &nbsp;·&nbsp; var 1/λ²<br />
            Uniform(a,b) &nbsp;&nbsp;&nbsp;&nbsp; mean (a+b)/2 &nbsp;·&nbsp; var (b−a)²/12<br />
            Normal(μ,σ²) &nbsp;&nbsp;&nbsp;&nbsp; mean μ &nbsp;·&nbsp; var σ² &nbsp;&nbsp;<span style={{ color: tk.textDim }}>(68 / 95 / 99.7 at 1σ / 2σ / 3σ)</span><br />
          </div>
          <P>Two derived facts worth memorizing: the maximum of n independent Uniform(0,1) has mean n/(n+1), and the k-th smallest
            of n has mean k/(n+1) — the n points cut the interval into n+1 equal expected pieces. That single picture answers a
            whole family of order-statistic questions.</P>
        </Card>
        <Q d="must" q="Why is the variance of a sum not always the sum of the variances, when the expectation always is?"
           a={"Expectation is linear over any random variables, full stop: E[X+Y] = E[X] + E[Y] with no assumption at all. Variance is a quadratic, so Var(X+Y) = Var(X) + Var(Y) + 2Cov(X,Y), and the cross term vanishes only when X and Y are uncorrelated.\n\nThis asymmetry is exactly why linearity of expectation is the strongest tool in the interview kit: you can decompose a horribly dependent count into indicators and add the pieces without ever arguing about independence. The moment the question asks for a variance or a probability rather than a mean, the dependence comes back and you have to handle it."} />
        <Q d="medium" q="When does the Poisson distribution show up, and why do quant and HFT problems keep reaching for it?"
           a={"Poisson is the law of rare events in continuous time: if events arrive independently at a constant average rate λ, the count in a unit interval is Poisson(λ) and the gaps between events are Exponential(λ). It is also the limit of Binomial(n, λ/n) as n grows.\n\nIt shows up in these domains because order arrivals, message arrivals on a feed, and packet arrivals are often modelled this way as a first approximation. The useful consequences: mean equals variance (so a count much more variable than its mean is evidence the Poisson model is wrong — real order flow is bursty and clustered, not Poisson); the gaps are memoryless; and merging independent Poisson streams of rates λ₁ and λ₂ gives a Poisson stream of rate λ₁+λ₂.\n\nSaying the model's assumption is violated is a better answer than applying it silently."} />
      </S>

      <S title="The twelve classics — derive, do not recite" c={tk.amber}>
        <Q d="must" q="Expected number of fair coin flips to first see HH? To first see HT? Why are they different?"
           a={"HH takes 6 flips on average; HT takes 4.\n\nFirst-step for HT: let a be the expected additional flips from the start, b from a state where the last flip was H. From the start, one flip: half the time you get H and move to state b, half the time T and stay. a = 1 + ½b + ½a, so a = 2 + b. From b, one flip: half the time T finishes it, half the time H keeps you in b. b = 1 + ½·0 + ½b, so b = 2. Therefore a = 4.\n\nSame for HH: a = 1 + ½b + ½a and b = 1 + ½·0 + ½a, giving a = 2 + b and b = 1 + ½a, so a = 6.\n\nThe intuition is the one to say out loud: HH can be destroyed by its own failure. If you are one H into HH and flip T, you lose all progress. If you are one H into HT and flip H, you are still one H into HT — the pattern overlaps with itself, so the failure is free. Self-overlapping patterns wait longer.\n\nThe martingale shortcut (the 'ABRACADABRA' argument) makes this mechanical: for a fair coin the expected wait for a pattern is the sum of 2^k over every k such that the pattern's first k characters equal its last k characters. HH overlaps at k=1 and k=2, giving 2 + 4 = 6. HT overlaps only at k=2, giving 4."} />
        <Q d="must" q="You roll a fair die. You may keep the value or re-roll once and keep whatever comes. What is the game worth? What about two re-rolls?"
           a={"With one re-roll: the fresh roll is worth 3.5, so keep anything above 3.5 — that is 4, 5, 6 — and re-roll 1, 2, 3. Value = (3/6)·3.5 + (1/6)(4+5+6) = 1.75 + 2.5 = 4.25.\n\nWith two re-rolls, solve backwards. The continuation value after the first roll is now 4.25, so on the first roll keep only 5 or 6. Value = (2/6)·5.5 + (4/6)·4.25 = 11/6 + 17/6 = 14/3 ≈ 4.667.\n\nThe method matters more than the numbers: this is backward induction, and the rule 'keep if the value exceeds the continuation value' is the same rule that prices an American option and the same rule behind every optimal-stopping question you will be asked. Solve from the last decision backwards, always."} />
        <Q d="medium" q="A stick of length 1 is broken at two uniformly random points. What is the probability the three pieces form a triangle?"
           a={"1/4.\n\nLet the two cut points be X and Y, uniform on the unit square. The three pieces form a triangle exactly when no piece exceeds 1/2 (the triangle inequality, since the total is 1 — any piece longer than half is longer than the other two combined).\n\nSplit on the order. If X < Y, the pieces are X, Y−X, 1−Y and the three conditions are X < ½, Y−X < ½, Y > ½. That region is a triangle in the unit square with area 1/8. By symmetry the X > Y case contributes another 1/8. Total 1/4.\n\nSanity check to say out loud: the answer must be well under 1/2, because it is easy to get one long piece. And note the different problem that is often confused with it — break the stick once, then break the longer piece — which gives ln(2) − 1/2 ≈ 0.193, not 1/4. Ask which version is meant."} />
        <Q d="medium" q="Expected number of draws to collect all n coupon types, one uniform type per draw?"
           a={"n·H_n = n(1 + 1/2 + … + 1/n) ≈ n ln n + γn, with γ ≈ 0.577.\n\nDecompose by stages. Once you hold k distinct types, each draw is new with probability (n−k)/n, so the wait for the next new one is Geometric with mean n/(n−k). Sum over k from 0 to n−1: n(1/n + 1/(n−1) + … + 1/1) = n·H_n.\n\nThe fact worth carrying: the last few coupons dominate. Collecting the first half costs about n ln 2 ≈ 0.69n draws; the single last coupon costs n draws by itself. That shape — a long tail owned by the rarest case — is the same shape as tail latency, and it is a good bridge to make if the conversation is heading toward systems."} />
        <Q d="medium" q="Fair coin, you start with k dollars and bet one dollar per flip until you hit 0 or N. Probability you reach N? Expected number of flips?"
           a={"Probability k/N. Expected duration k(N−k).\n\nProbability: your wealth is a martingale (each bet is fair), and the game stops at 0 or N. Optional stopping gives k = E[final] = N·p + 0·(1−p), so p = k/N. Say the martingale sentence — it is the whole solution.\n\nDuration: Wₙ² − n is also a martingale, so at the stopping time E[W_τ²] = k² + E[τ]. Since E[W_τ²] = N²·(k/N) = kN, we get E[τ] = kN − k² = k(N−k).\n\nSanity checks: p is linear in k, which is what fairness demands. The duration is maximized in the middle and zero at the boundaries. And if the coin is biased the martingale changes to (q/p)^W, which is worth mentioning as the natural generalization even if they do not ask."} />
        <Q d="medium" q="Three prisoners, or Monty Hall, or the boy-girl problem: what is the single mistake all of them exploit?"
           a={"Conditioning on the event that actually happened rather than on the event you were told about — and forgetting that the information source has a protocol.\n\nMonty Hall: switching wins 2/3 because the host must open a goat door and must avoid your door. Those two constraints leak information about the remaining door. If the host opened a door at random and it happened to show a goat, switching is only 1/2. The answer depends entirely on the protocol, so state the protocol before answering.\n\nBoy-girl: 'a family with two children, at least one is a boy' gives 1/3 for two boys, because the sample space is BB, BG, GB. But 'I met one of the children and it was a boy' gives 1/2, and 'the older is a boy' gives 1/2. Same words, different sample spaces.\n\nThe transferable habit: when a question hinges on evidence, write down how the evidence was generated before you compute anything. In the job this is the same instinct that catches look-ahead bias in a backtest."} />
        <Q d="medium" q="A test is 99% accurate for a disease that affects 1 in 10,000. You test positive. What is the probability you have it?"
           a={"About 1%.\n\nOdds form is fastest. Prior odds 1:9,999. The likelihood ratio is 0.99 / 0.01 = 99. Posterior odds are 99:9,999, which is about 1:101, so roughly 0.98%.\n\nThe base rate dominates because false positives are drawn from a pool ten thousand times larger than true positives. Out of a million people: 100 have it and about 99 test positive; 999,900 do not and about 9,999 test positive anyway.\n\nThis question is not really about disease. It is the same arithmetic as an alerting system with a low true-event rate, or a strategy signal that fires rarely: a detector with a great-sounding accuracy can still be wrong almost every time it fires. If you have ever tuned an alert threshold, say so — the connection is the interesting part of the answer."} />
        <Q d="medium" q="Draw uniformly from [0,1] repeatedly until the numbers stop increasing. Expected number of draws?"
           a={"e ≈ 2.718.\n\nLet N be the index of the first draw that breaks the increase, so you have made N draws. P(the first k draws are increasing) = 1/k!, because all k! orderings of k distinct uniforms are equally likely and exactly one is sorted.\n\nUse the tail-sum formula: E[N] = Σ_{k≥0} P(N > k) = Σ_{k≥0} P(first k are increasing) = Σ_{k≥0} 1/k! = e.\n\nThis is the cleanest advertisement for the tail-sum tool. The PMF here is annoying; the tail probability is a one-line symmetry argument. Whenever P(X ≥ k) is easier than P(X = k), stop trying to write the PMF.\n\nA companion result with the same flavour: the expected number of draws from [0,1] until the running sum exceeds 1 is also e."} />
        <Q d="hard" q="Expected number of records (running maxima) in a random permutation of n distinct numbers?"
           a={"H_n = 1 + 1/2 + … + 1/n ≈ ln n + 0.577.\n\nIndicator per position: element i is a record exactly when it is the largest of the first i. By symmetry among those i elements that has probability 1/i, with no independence needed. Linearity gives Σ 1/i.\n\nThe punchline to deliver: records are logarithmically rare. In a million random values you expect about fourteen new maxima ever. This is why 'the maximum keeps getting beaten' is a bad model of a random series, and it is the reason a randomized incremental algorithm that only does work on a record is cheap in expectation. The same H_n also gives the expected number of comparisons in the randomized-pivot analysis and the expected cost of randomized incremental construction.\n\nVariance, if pushed: the indicators here are actually independent, which is a small surprise worth mentioning, so the variance is Σ (1/i)(1 − 1/i) = H_n − H_n^(2)."} />
        <Q d="hard" q="n people, each with an assigned seat. The first sits at random; each later person takes their own seat if free, otherwise a random free one. Probability the last person gets their own seat?"
           a={"1/2, for every n ≥ 2.\n\nThe argument to give: at every point, the only two seats that can end the process are seat 1 and seat n. Whenever a displaced person chooses at random, seat 1 and seat n are exchangeable — nothing in the process has ever distinguished them — so the first of the two to be taken is equally likely to be either. The last person gets their own seat exactly when seat 1 is taken first, which is 1/2.\n\nThis is the purest symmetry question in the standard set. The recursion also works and gives 1/2, but the symmetry argument is what the interviewer is listening for, and it generalizes instantly: the probability that the k-th person from the end gets their seat is 1 − 1/(n−k+2), and the answer is 1/2 regardless of n, which you can offer as a check."} />
        <Q d="hard" q="You see a stream of items of unknown length and can hold one. How do you keep a uniformly random item, and how do you prove it?"
           a={"Reservoir sampling. Keep the first item; when item i arrives, replace the held item with probability 1/i.\n\nProof by induction: suppose after i−1 items every one of them is held with probability 1/(i−1). Item i is kept with probability 1/i. Any earlier item survives if it was held (1/(i−1)) and was not replaced (1 − 1/i = (i−1)/i), giving 1/(i−1) · (i−1)/i = 1/i. So all i items are equally likely.\n\nFor k items instead of one, keep the first k, then for item i > k replace a uniformly chosen slot with probability k/i.\n\nThis is the question that sits exactly on the boundary between the probability round and the coding round, which is why it is worth being fast at. It is also genuinely useful: it is how you sample a live market-data feed or a log stream for diagnostics without knowing the length and without buffering it."} />
        <Q d="hard" q="Two players alternately flip a fair coin; the first to get heads wins. What is the first player's chance? Now make it: the first to get two heads in a row."
           a={"First version: 2/3. Let p be the first player's win probability. They win immediately with probability 1/2; otherwise the roles swap and the opponent now has probability p, so p = 1/2 + 1/2(1 − p), giving p = 2/3. Equivalently sum the geometric series 1/2 + 1/8 + 1/32 + … = (1/2)/(1 − 1/4) = 2/3.\n\nThe second version is the point of the question. The state is no longer just 'whose turn' — you need whose turn AND whether the previous flip in that player's own sequence was a head, because the sequences interleave. Set up the states carefully, write the linear system, and solve. Most candidates get this wrong by reusing the first answer's shape.\n\nWhat is being tested is whether you notice that the state space grew. That is the same skill as noticing a cache in a system has state you did not model. Say 'let me re-define the state' out loud and you have already earned most of the credit."} />
      </S>

      <S title="Traps that cost the offer" c={tk.red}>
        <G cols={1} items={[
          { t: "E[1/X] ≠ 1/E[X]", d: "Jensen's inequality: for a convex function, E[f(X)] ≥ f(E[X]). 1/x is convex on the positives, so E[1/X] ≥ 1/E[X], strictly unless X is constant. The same trap appears as E[X²] ≥ E[X]² (that gap IS the variance) and as the difference between the mean of a ratio and the ratio of means in any performance metric." },
          { t: "The average of averages", d: "Averaging per-group means without weighting by group size is Simpson's paradox waiting to happen. Every metric you report as 'average latency across services' or 'average return across strategies' has this bug unless you weight it." },
          { t: "Assuming independence because nothing said otherwise", d: "State it as an assumption or derive without it. Linearity of expectation lets you avoid the assumption entirely for means, which is exactly why it is the first tool to reach for." },
          { t: "Conditioning on the outcome instead of the protocol", d: "Monty Hall, the boy-girl problem, and every survivorship-bias question in finance are the same error. Ask how the information reached you." },
          { t: "Forgetting that a maximum is not a mean", d: "For n independent uniforms, the mean is 1/2 no matter what n is, but the expected maximum is n/(n+1) and marches to 1. Tail questions and average questions have different answers; latency work lives entirely in the gap." },
          { t: "Answering a puzzle you recognize without deriving it", d: "If you have seen it, say 'I have seen this, the answer is X, let me show why' and then derive it. Reciting an answer you cannot derive is the worst possible outcome, because the follow-up will change one parameter." },
        ]} />
      </S>

      <S title="Where this becomes the job: Monte Carlo you can defend" c={tk.emerald}>
        <B type="tip">
          For a quant <em>developer</em>, the probability round is the filter and this section is the work. A researcher hands you a
          simulation; you have to make it correct, reproducible, and fast enough to run a thousand times.
        </B>
        <Q d="must" q="A Monte Carlo estimate is not accurate enough. What do you do first, and why is 'run more paths' usually the wrong answer?"
           a={"The standard error of a Monte Carlo mean is σ/√N. To halve the error you need four times the paths; for one more decimal digit you need a hundred times. Compute is the most expensive lever available and it has the worst exponent, so reach for it last.\n\nCheaper levers, in the order to try them:\n\n1. Report the standard error at all. An estimate without an error bar cannot be called insufficient, and half the time the estimate is already inside tolerance and nobody knew.\n2. Antithetic variates: for each path using U, also run 1−U. If the payoff is monotone in U the two are negatively correlated and the pair's variance falls, often substantially, for the same number of random draws.\n3. Control variates: subtract a correlated quantity whose exact mean you know and add its mean back. Variance falls by a factor of 1/(1−ρ²) where ρ is the correlation with the control. With ρ = 0.95 that is a twentyfold reduction, equivalent to twenty times the paths.\n4. Common random numbers: when comparing two configurations, drive both with the same stream. The difference's variance collapses even when each estimate is noisy, because the noise cancels.\n5. Stratification or quasi-random sequences when the dimension is low.\n\nOnly after those, buy compute. And when you do, check that the generator is actually independent across threads — a per-thread generator seeded from the same value silently reduces your effective N to N/threads while the error bar keeps claiming otherwise."} />
        <Q d="must" q="Your simulation gives a different answer on a second run, and a different one again on a different machine. Walk through it."
           a={"Separate three causes before touching anything.\n\nUnseeded randomness. Different answers on the same binary and machine mean the seed is not fixed, or a thread count changed the number of streams drawn. Fix: one explicit seed in configuration, one generator per worker seeded deterministically from it (a counter-based generator, or a stream-splitting API), and the seed recorded in the output. Never seed from the clock in anything whose result you will be asked to reproduce.\n\nNon-deterministic reduction order. Floating-point addition is not associative, so a parallel sum over the same values in a different order gives a different last few bits, and each run's thread scheduling changes that order. Fix: a deterministic reduction — fixed-size chunks summed in index order, or pairwise/Kahan summation. This is the cause people miss, and the symptom is agreement to about ten digits rather than gross disagreement.\n\nDifferent machine, same seed. Now suspect the toolchain: fused multiply-add contracting two operations into one with a single rounding, different vector widths changing the reduction tree, an x87 80-bit intermediate on an old target, a different libm giving a differently-rounded transcendental, or -ffast-math having been enabled somewhere. Fix: pin the flags, disable FP contraction where bit-reproducibility is a requirement, and be explicit about which math library you rely on.\n\nThe closing judgement is the part interviewers care about: decide whether the difference is real. A relative difference near 1e-16 per operation accumulated over the reduction is rounding and does not matter for a result with a 1% Monte Carlo error bar. A difference larger than the standard error is a bug. Say which one you are looking at before you spend a day on it."} />
        <Q d="medium" q="Why does 'the strategy makes money in the backtest' so often turn out to be an artifact, and which artifacts should you be able to name?"
           a={"Because a backtest is an estimator with a much larger variance and a much larger bias than its single reported number suggests.\n\nThe named artifacts:\n\nLook-ahead bias — the simulation uses information that was not available at that timestamp. Common forms: using the close to decide a trade at the close, a data field revised after the fact, or joining on a date that is the publication date rather than the availability date.\n\nSurvivorship bias — the universe contains only instruments that still exist. Delisted, defaulted and merged names are exactly the losing outcomes, so removing them raises every historical return.\n\nMultiple testing — try two hundred variants at the 5% level and roughly ten look significant by construction. The reported result is the maximum over the search, and the maximum of noise is not zero. This is the single largest one.\n\nOverfitting to a regime — the parameters encode one volatility environment.\n\nUnmodelled costs — spread, market impact, borrowing, and the fact that filling at the mid is not a fill.\n\nThe useful engineering answer is that these are testable, not merely cautionary: hold out data you have never looked at, count and report the number of variants tried, replay the data through the same code path as production so that look-ahead is structurally impossible rather than merely intended, and check that the result survives realistic costs."} />
        <Q d="medium" q="How do you sanity-check a probabilistic result in ninety seconds, in an interview or in code review?"
           a={"Four checks, in this order, and all of them are cheap:\n\nExtreme cases. Set n = 1 or n = 2 and see whether the formula gives the obvious answer. Set p = 0 or p = 1. Most algebra errors die here.\n\nMonotonicity and limits. Should the answer grow with n? Should it approach a limit you can name? The coupon collector must grow faster than n; the seating problem must not depend on n at all; a probability must stay in [0,1] for every parameter value.\n\nUnits and type. An expected count must be non-negative and can exceed 1. A probability cannot. Confusing the two is the most common careless error, and it is instantly visible.\n\nA thirty-second simulation. In code review this is not optional — write the ten-line loop and compare. If the closed form and the simulation disagree, one of them is wrong and you have learned that in half a minute rather than after the strategy is live.\n\nIn an interview, doing the first three out loud, unprompted, reads as maturity more than any single correct answer does."} />
      </S>

      <S title="A four-week plan for this competency" c={tk.blue}>
        <G cols={2} items={[
          { t: "Week 1 — the tools", d: "Work the eight-tool table until you can name the tool from the question's shape in under ten seconds. Drill by reading only the first sentence of a problem and saying the tool, without solving." },
          { t: "Week 2 — the classics", d: "Derive all twelve above from scratch on paper, out loud, timed at three minutes each. Then change one parameter in each and re-derive: biased coin, three patterns, n sides instead of six." },
          { t: "Week 3 — distributions and estimators", d: "Mean and variance of the seven distributions cold. Then: standard error, confidence interval, and the four variance-reduction techniques, each implemented once in twenty lines." },
          { t: "Week 4 — say it out loud", d: "The gap between knowing and passing is verbalization. Record yourself solving five problems. If you cannot follow your own recording, the interviewer could not either." },
        ]} />
        <B type="warn">
          One honest scoping note. This module is calibrated for engineering and quant-developer loops, where probability is a
          reasoning filter. Quant <em>research</em> loops go considerably deeper — stochastic calculus, time series, statistical
          inference — and that is a different and much longer syllabus. Choose the target before you spend six months on the wrong one.
        </B>
      </S>
    </div>
  );
}
