#!/usr/bin/env node
/* Generate the client-safe content index at build time.
   Guide BODIES stay on disk and are read by server components, so 580 KB of
   markdown never reaches the browser bundle. Only metadata and headings ship. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const guidesDir = path.join(root, 'content/guides');
const outDir = path.join(root, 'src/data/generated');
fs.mkdirSync(outDir, { recursive: true });

const stripMd = (s) => String(s).replace(/<[^>]+>/g, '').replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
  .replace(/`([^`]+)`/g, '$1').replace(/\*\*?([^*]+)\*\*?/g, '$1').trim();
export const headingId = (t) => String(t).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

/* ── guides ─────────────────────────────────────────────────────────── */
const files = fs.readdirSync(guidesDir).filter((f) => f.endsWith('.md')).sort();
const guides = files.map((file) => {
  const raw = fs.readFileSync(path.join(guidesDir, file), 'utf8');
  const name = file.replace(/\.md$/, '');
  const meta = /^<!--([\s\S]*?)-->/.exec(raw)?.[1] || '';
  const get = (k) => (new RegExp(`^${k}:\\s*(.*)$`, 'm').exec(meta)?.[1] || '').trim();
  const body = raw.replace(/^<!--[\s\S]*?-->\s*/, '');
  const title = stripMd(/^#\s+(.*)/m.exec(body)?.[1] || name);
  const headings = [];
  for (const line of body.split('\n')) {
    const m = /^(#{2,3})\s+(.*)$/.exec(line);
    if (m) {
      const text = stripMd(m[2]).replace(/\(.*?\)/g, '').trim();
      if (text) headings.push({ level: m[1].length, text, id: headingId(text) });
    }
  }
  const words = body.split(/\s+/).length;
  return {
    num: name.slice(0, 2), name, file, title, headings,
    category: get('category') || 'Other', tags: get('tags'),
    difficulty: get('difficulty'),
    readTime: get('readTime') || `${Math.max(1, Math.round(words / 220))} min`,
    words,
  };
});

/* A guide's number is its URL. Two files sharing one prefix would make one of
   them permanently unreachable, which is exactly the bug this guard exists to
   stop: it happened once, silently, and cost a whole guide. */
const byNum = new Map();
for (const g of guides) {
  if (byNum.has(g.num)) {
    console.error(`\nFATAL: guides "${byNum.get(g.num).file}" and "${g.file}" share the number ${g.num}.`);
    console.error('Rename one of them: the numeric prefix is the guide\'s URL and must be unique.\n');
    process.exit(1);
  }
  byNum.set(g.num, g);
}

/* ── legacy Q&A questions, mapped to the module that renders them ────── */
const qRe = /<Q\s+[\s\S]*?\sq=(?:"((?:[^"\\]|\\.)*)"|\{"((?:[^"\\]|\\.)*)"\})/g;
const prep = [];
const seen = new Set();
const push = (module, question) => {
  const key = module + '|' + question;
  if (!question || seen.has(key)) return;
  seen.add(key); prep.push({ module, question });
};
const libSrc = fs.readFileSync(path.join(root, 'src/legacyLibrary.jsx'), 'utf8');
const mods = [...libSrc.matchAll(/\n([a-z0-9_]+):\(\)=>/g)].map((m) => ({ id: m[1], offset: m.index }));
const moduleAt = (offset) => { let cur = null; for (const m of mods) { if (m.offset <= offset) cur = m.id; else break; } return cur; };
for (const m of libSrc.matchAll(qRe)) {
  const q = (m[1] || m[2] || '').replace(/\\"/g, '"').replace(/\\n/g, ' ').trim();
  const mod = moduleAt(m.index);
  if (mod) push(mod, q);
}
for (const f of fs.readdirSync(path.join(root, 'src/modules')).filter((f) => f.endsWith('.jsx'))) {
  const id = f.replace(/\.jsx$/, '');
  const src = fs.readFileSync(path.join(root, 'src/modules', f), 'utf8');
  for (const m of src.matchAll(new RegExp(qRe.source, 'g'))) {
    push(id, (m[1] || m[2] || '').replace(/\\"/g, '"').replace(/\\n/g, ' ').trim());
  }
}

const banner = '/* GENERATED by scripts/build-content.mjs — do not edit. */\n';
/* ── headline numbers ────────────────────────────────────────────────────
   Generated, never hand-written, so the marketing copy on the landing page
   cannot drift away from what the product actually contains. */
const dsaSrc = fs.readFileSync(path.join(root, 'src/dsaData.jsx'), 'utf8');
/* The bank is PROBLEMS + NVIDIA_PROBLEMS only; every other collection in that
   file (bug hunts, quizzes, concepts) also has `id:` fields, so slice first.
   Same method as scripts/check-curriculum.mjs, which asserts the same number. */
const seg = (from, to) => dsaSrc.slice(dsaSrc.indexOf(from), dsaSrc.indexOf(to));
const bankSrc = seg('export const PROBLEMS', 'export const NVIDIA_PROBLEMS')
              + seg('export const NVIDIA_PROBLEMS', 'export const CPP_CONCEPTS');
const problems = new Set([...bankSrc.matchAll(/^\s*id:\s*(\d+),/gm)].map((m) => +m[1])).size;
const labsJson = JSON.parse(fs.readFileSync(path.join(root, 'src/data/labs.json'), 'utf8'));
const rolesSrc = fs.readFileSync(path.join(root, 'src/data/roles.js'), 'utf8');
const stats = {
  problems,
  labs: labsJson.labs.length,
  tracks: labsJson.tracks.length,
  guides: guides.length,
  guideWords: guides.reduce((a, g) => a + g.words, 0),
  questions: prep.length,
  roles: (rolesSrc.match(/^\s{4}id: "/gm) || []).length,
  competencies: (rolesSrc.match(/\{ id: "[a-z]-[a-z]+", name:/g) || []).length,
  generatedAt: new Date().toISOString().slice(0, 10),
};
fs.writeFileSync(path.join(outDir, 'stats.js'), banner + 'export const STATS = ' + JSON.stringify(stats, null, 1) + ';\n');


fs.writeFileSync(path.join(outDir, 'guides.js'),
  banner + 'export const GUIDES = ' + JSON.stringify(guides, null, 1) + ';\n' +
  'export const guideByNum = (n) => GUIDES.find((g) => g.num === String(n));\n');
/* Human-readable module labels, read out of the GROUPS table in the library. */
const labels = {};
const groupsSrc = libSrc.slice(libSrc.indexOf('export const GROUPS'));
for (const m of groupsSrc.matchAll(/\{id:"([a-z0-9_]+)",label:"([^"]+)"/g)) labels[m[1]] = m[2];

fs.writeFileSync(path.join(outDir, 'prepIndex.js'),
  banner + 'export const PREP_INDEX = ' + JSON.stringify(prep) + ';\n' +
  'export const PREP_MODULE_LABELS = ' + JSON.stringify(labels, null, 1) + ';\n');

const kb = (n) => (n / 1024).toFixed(0) + ' KB';
const bodyBytes = files.reduce((a, f) => a + fs.statSync(path.join(guidesDir, f)).size, 0);
console.log(`content: ${guides.length} guides (${kb(bodyBytes)} of bodies kept server-side), ` +
  `${prep.length} Q&A questions, ${Object.keys(labels).length} module labels, index ${kb(fs.statSync(path.join(outDir, 'guides.js')).size)}`);
